Models/Batch.cs
using System.ComponentModel.DataAnnotations;

namespace SchoolManagementSystem.Models
{
    public class Batch
    {
        [Key]
        public int Id { get; set; }
        [Required]
        public string BatchCode { get; set; }
        public string Year { get; set; }
        public List<Student>? Students { get; set; }
    }
}

Controllers/BatchController.cs
using CourseManagementSystem.ViewModels.BatchVM;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using SchoolManagementSystem.Data;
using SchoolManagementSystem.Models;
using SchoolManagementSystem.ViewModels.BatchVM;
using SchoolManagementSystem.ViewModels.CourseVM;

namespace SchoolManagementSystem.Controllers
{
    [Authorize]
    public class BatchController : Controller
    {
        private readonly DataContext _db;

        public BatchController(DataContext db)
        {
            _db = db;
        }
        public IActionResult GetBatches()
        {
            var batches = _db.Batches.ToList();
            return View(batches);
        }

        public IActionResult CreateBatch()
        {
            return View(new CreateBatchVM());
        }

        [HttpPost]
        public IActionResult CreateBatch(CreateBatchVM model)
        {
            if (ModelState.IsValid)
            {
                var batch = new Batch()
                {
                    BatchCode = model.BatchCode,
                    Year = model.Year
                };
                _db.Batches.Add(batch);
                if (_db.SaveChanges() > 0)
                {
                    return RedirectToAction("GetBatches");
                }
            }
            return View();
        }
        public IActionResult EditBatch(int? id)
        {
            if (id == null || id == 0)
            {
                return NotFound();
            }
            var batch = _db.Batches.FirstOrDefault(b => b.Id == id);
            if (batch == null)
            {
                return NotFound();
            }
            var batchVM = new EditBatchVM()
            {
                Id = batch.Id,
                BatchCode = batch.BatchCode,
                Year = batch.Year
            };
            return View(batchVM);

        }
        [HttpPost]
        public IActionResult EditBatch(EditBatchVM model)
        {
            if (ModelState.IsValid)
            {
                var batch = new Batch()
                {
                    Id = model.Id,
                    BatchCode = model.BatchCode,
                    Year = model.Year
                };
                _db.Batches.Update(batch);
                if (_db.SaveChanges() > 0)
                {
                    return RedirectToAction("GetBatches");
                }
            }
            return View();
        }
        public IActionResult DeleteBatch(int? id)
        {
            if (id == null || id == 0)
            {
                return NotFound();
            }
            var course = _db.Batches.FirstOrDefault(b => b.Id == id);
            if (course == null)
            {
                return NotFound();
            }
            var courseVM = new DeleteBatchVM()
            {
                Id = course.Id,
                BatchCode = course.BatchCode,
                Year = course.Year
            };
            return View(courseVM);
        }
        [HttpPost]
        public IActionResult DeleteBatch(DeleteBatchVM model)
        {
            var obj = _db.Batches.FirstOrDefault(b => b.Id == model.Id);
            if (obj == null)
            {
                return NotFound();
            }
            _db.Batches.Remove(obj);
            if (_db.SaveChanges() > 0)
            {
                return RedirectToAction("GetBatches");
            }

            return View();
        }
    }
}

Views/Batch/CreateBatch.cshtml
@using SchoolManagementSystem.ViewModels.BatchVM;
@model CreateBatchVM

<div class="container">
    <form method="post" class="mt-5">
        <div class="mb-3">
            <label asp-for="BatchCode" class="form-label">Batch Code</label>
            <input type="text" asp-for="BatchCode" class="form-control" id="BatchCode">
            <span asp-validation-for="BatchCode" class="text-danger"></span>
        </div>
        <div class="mb-3">
            <label asp-for="Year" class="form-label">Year</label>
            <input type="text" asp-for="Year" class="form-control" id="Year">
            <span asp-validation-for="Year" class="text-danger"></span>
        </div>   
        <button type="submit" class="btn btn-primary">Submit</button>
    </form>
</div>

Views/Batch/DeleteBatch.cshtml
@using CourseManagementSystem.ViewModels.BatchVM;
@model DeleteBatchVM

<div class="container">
    <form method="post" class="mt-5">
        <div class="mb-3">
            <label asp-for="BatchCode" class="form-label">Batch Code</label>
            <input type="text" asp-for="BatchCode" class="form-control" id="BatchCode" disabled>
        </div>
        <div class="mb-3">
            <label asp-for="Year" class="form-label">Year</label>
            <input type="text" asp-for="Year" class="form-control" id="Year" disabled>
        </div>
        <button type="submit" class="btn btn-primary">Delete</button>
    </form>
</div>

Views/Batch/EditBatch.cshtml
@using CourseManagementSystem.ViewModels.BatchVM;
@model EditBatchVM

<div class="container">
    <form method="post" class="mt-5">
        <div class="mb-3">
            <label asp-for="BatchCode" class="form-label">Batch Code</label>
            <input type="text" asp-for="BatchCode" class="form-control" id="BatchCode">
            <span asp-validation-for="BatchCode" class="text-danger"></span>
        </div>
        <div class="mb-3">
            <label asp-for="Year" class="form-label">Year</label>
            <input type="text" asp-for="Year" class="form-control" id="Year">
            <span asp-validation-for="Year" class="text-danger"></span>
        </div>
        <button type="submit" class="btn btn-primary">Submit</button>
    </form>
</div>

Views/Batch/GetBatches.cshtml
@model List<Batch>

<div class="container">
    <div>
        <a class="btn btn-primary mt-5" asp-area="" asp-controller="Batch" asp-action="CreateBatch">Add New Batch</a>
    </div>

    <div class="border rounded mt-2">
        <table id="myTable" class="table table-hover">
            <thead>
                <tr>
                    <th scope="col">Id</th>
                    <th scope="col">BatchCode</th>
                    <th scope="col">Year</th>
                    <th scope="col">Actions</th>

                </tr>
            </thead>
            <tbody>
                @foreach (var batch in Model)
                {
                        <tr class="table-active">
                            <td>@batch.Id</td>
                            <td>@batch.BatchCode</td>
                            <td>@batch.Year</td>
                            <td>
                                <a class="btn btn-warning" asp-controller="Batch" asp-action="EditBatch" asp-route-id="@batch.Id">Edit</a>
                                <a class="btn btn-danger" asp-controller="Batch" asp-action="DeleteBatch" asp-route-id="@batch.Id">Delete</a>
                            </td>
                        </tr>
                }

            </tbody>
        </table>
    </div>
</div>